[AST-43] Flag mapped pins that have not been directly imported as warnings
Azure-Sphere-Tools/azsphere-hardware-definition-tools pull request #24
Opened 2021-07-20 17:32 UTC by jack870131

2021-07-20 22:16 UTC, Beyhum approved these changes

2021-07-21 08:44 UTC, dorinbotan requested changes
Minor change in the warning message can make it more informative.

2021-07-21 08:44 UTC, dorinbotan commented on server/src/validator.ts
> +							message: `${mappedTo} is indirectly imported by ${hwDefinition.uri}`,
Might be more useful to point to the file where this mapping has been imported from (mappedToPath), or, even better, the file where it must be included from (the one in hwDefinition.imports).

Example of option 1:
MT3620_GPIO06 indirectly imported from .../mt3620.json

Example of option 2:
MT3620_GPIO06 indirectly imported from .../mt3620_sk.json. Use ../avnet_mt3620_sk.json instead.

2021-07-21 16:07 UTC, jack870131 commented on server/src/validator.ts
> +							message: `${mappedTo} is indirectly imported by ${hwDefinition.uri}`,
Updated. Not sure if it follows what you suggested, so pls have a look again. Thx.

2021-07-22 08:59 UTC, Beyhum commented on server/src/validator.ts
> +							message: `${mappedTo} is indirectly imported by ${hwDefinition.uri}`,
I think the amount of searching done to find the other pin mapping is a bit too expensive, keeping it as 
"MT3620_GPIO06 is indirectly imported from .../mt3620.json" might be better for now

2021-07-22 11:15 UTC, dorinbotan approved these changes
Looks good.

2021-07-22 11:17 UTC, merged