Visual studio porting
Azure-Sphere-Tools/azsphere-hardware-definition-tools pull request #38
Opened 2021-08-09 14:44 UTC by Beyhum

2021-08-09 23:57 UTC, dorinbotan requested changes

2021-08-09 23:57 UTC, dorinbotan commented on visualstudio-extension/AZSphereHardwareDefinitionTools/AZSphereHardwareDefinitionToolsPackage.vsct
> +          <ButtonText>Port to another hardware definition</ButtonText>
The first button says "Hardware Definition File", this one is "hardware definition".
Better to make both uppercase or lowercase.

2021-08-09 23:57 UTC, dorinbotan commented on vscode-extension/src/extension.ts
> +    window.showErrorMessage('The current file is not a valid Hardware Definition. Navigate to a tab with a valid Hardware Definition to port from.');
This message is clearer than the previous one but does not fit in an unwrapped popup. I guess it's ok.

2021-08-09 23:57 UTC, dorinbotan commented on vscode-extension/src/extension.ts
>      window.showErrorMessage('Navigate to the tab with the Hardware Definition to port from.');
Can be rewritten as "Navigate to a tab with a valid Hardware Definition to port from." to match the following error message.

2021-08-09 23:57 UTC, dorinbotan commented on vscode-extension/src/extension.ts
> +            if (openNew == undefined) {
did you mean (chosenFile == undefined) ?

2021-08-09 23:57 UTC, dorinbotan commented on visualstudio-extension/AZSphereHardwareDefinitionTools/PortHardwareDefinitionHandler.cs
> +          await CreateAndDisplayInfoBarAsync($"Failed to port hardware definition file {originalHwDefFileName}", await CurrentFilePathAsync());
Since the file we are porting from is currently open, may be more useful to tell the user where we tried to port to (portedPath).

2021-08-09 23:57 UTC, dorinbotan commented on visualstudio-extension/AZSphereHardwareDefinitionTools/PortHardwareDefinitionHandler.cs
> +        string portedPath = await HardwareDefinitionLanguageClient.Instance.PortHardwareDefinitionAsync(selected.OriginalHwDefPath, selected.TargetHwDefPath);
Check TargetHwDef with ValidateHwDefinitionAsync, to inform the user why porting failed.
Or... in our current setup, porting can only fail if the TargetHwDef is invalid. (Am I not mistaken?)
If so, we can just change the Info message to tell the user that he is trying to port to an invalid HW Def.

2021-08-09 23:57 UTC, dorinbotan commented on visualstudio-extension/AZSphereHardwareDefinitionTools/PortHardwareDefinitionHandler.cs
> +      var isValidHwDef = await HardwareDefinitionLanguageClient.Instance.ValidateHwDefinitionAsync(currentFileUri);
UriFormatException is unhandled if no files are currently open (currentFileUri is undefined).

2021-08-10 01:51 UTC, Beyhum commented on visualstudio-extension/AZSphereHardwareDefinitionTools/PortHardwareDefinitionHandler.cs
> +        string portedPath = await HardwareDefinitionLanguageClient.Instance.PortHardwareDefinitionAsync(selected.OriginalHwDefPath, selected.TargetHwDefPath);
We run the validate command on the source hw def beforehand so this should only fail if the target is invalid. Will update the info message

2021-08-10 07:12 UTC, dorinbotan approved these changes

2021-08-10 11:01 UTC, merged